version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: listen
    versions:
    - 3.5.0
  - dependency-name: ferrum
    versions:
    - "0.10"
  - dependency-name: puma
    versions:
    - 5.2.0
    - 5.2.1
  - dependency-name: bootsnap
    versions:
    - 1.6.0
    - 1.7.0
    - 1.7.1
  - dependency-name: capybara
    versions:
    - 3.35.1
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: elliptic
    versions:
    - 6.5.4
