inherit_from:
  - .rubocop_base.yml

plugins:
  - rubocop-performance
  - rubocop-rails

AllCops:
  NewCops: enable
  DisplayCopNames: true
  SuggestExtensions: false
  Exclude:
    - db/schema.rb
    - vendor/**/*
    - tmp/**/*
    - .git/**/*
    - bin/*
    - 'node_modules/**/*'

Rails:
  Enabled: true

Rails/FilePath:
  Enabled: false

Rails/FindEach:
  Enabled: false

Rails/UnknownEnv:
  Environments:
    - development
    - production
    - test

Rails/EnvironmentVariableAccess:
  AllowReads: true

# 運用スクリプトではexit使用を許可
Rails/Exit:
  Exclude:
    - lib/**/*

# 運用スクリプトではupdate_all使用を許可
Rails/SkipsModelValidations:
  Exclude:
    - db/seeds/*
    - lib/**/*

Style/SignalException:
  Exclude:
    - app/avo/actions/*
