# JOYSOUNDのWebページから情報を取得するためのCSSセレクタ定義
selectors:
  # 楽曲詳細ページ
  song_detail:
    information_rows: "table tr"
    artist: "table tr td a[href^='/web/search/artist/']"
    songs: "#song-distribution [data-testid='card-information']"
    song_title: "p"
    platform_item: "li"
    error: "main"
