default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("PGUSER", "postgres") %>
  password: <%= ENV.fetch("PGPASSWORD", "postgres") %>
  host: <%= ENV.fetch("PGHOST", "localhost") %>
  port: <%= ENV.fetch("PGPORT", "5432") %>

development:
  primary:
    <<: *default
    database: touhou_karaoke_admin_development
  queue:
    <<: *default
    database: touhou_karaoke_admin_development_queue
    migrations_paths: db/queue_migrate

test:
  <<: *default
  database: touhou_karaoke_admin_test

production:
  primary:
    <<: *default
    database: touhou_karaoke_admin_production
    username: touhou_karaoke_admin
    password: <%= ENV['TOUHOU_KARAOKE_ADMIN_DATABASE_PASSWORD'] %>
  queue:
    <<: *default
    database: touhou_karaoke_admin_production_queue
    username: touhou_karaoke_admin
    password: <%= ENV['TOUHOU_KARAOKE_ADMIN_DATABASE_PASSWORD'] %>
    migrations_paths: db/queue_migrate
