name: Ruby

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/**'
      - '.ruby-version'
      - '.rubocop*.yml'
      - 'Gemfile'
      - 'Gemfile.lock'
      - 'Makefile'
      - 'Taskfile.yml'
      - 'mise.toml'
      - 'Procfile*'
      - 'Rakefile'
      - 'app/**'
      - 'bin/**'
      - 'config/**'
      - 'config.ru'
      - 'db/**'
      - 'devbox.json'
      - 'devbox.lock'
      - 'docker-compose.yml'
      - 'Dockerfile'
      - 'lib/**'
      - 'package.json'
      - 'process-compose.yaml'
      - 'public/**'
      - 'test/**'
      - 'vendor/**'
      - '.yarn/**'
      - '.yarnrc.yml'
      - 'yarn.lock'
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    paths:
      - '.github/workflows/**'
      - '.ruby-version'
      - '.rubocop*.yml'
      - 'Gemfile'
      - 'Gemfile.lock'
      - 'Makefile'
      - 'Taskfile.yml'
      - 'mise.toml'
      - 'Procfile*'
      - 'Rakefile'
      - 'app/**'
      - 'bin/**'
      - 'config/**'
      - 'config.ru'
      - 'db/**'
      - 'devbox.json'
      - 'devbox.lock'
      - 'docker-compose.yml'
      - 'Dockerfile'
      - 'lib/**'
      - 'package.json'
      - 'process-compose.yaml'
      - 'public/**'
      - 'test/**'
      - 'vendor/**'
      - '.yarn/**'
      - '.yarnrc.yml'
      - 'yarn.lock'

env:
  CI: "true"
  PGHOST: 127.0.0.1
  PGUSER: postgres
  PGPASSWORD: password
  RAILS_ENV: test
  SKIP_CSS_BUILD: "1"
  SKIP_JS_BUILD: "1"
  SKIP_YARN_INSTALL: "1"

permissions:
  contents: read

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:18.4-alpine3.24
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: password
        options: >-
          --health-cmd "PGPASSWORD=password psql -h 127.0.0.1 -U postgres -d postgres -c 'SELECT 1'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
          --health-start-period 10s

    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.1

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Set up Node.js
        uses: actions/setup-node@v7.0.0
        with:
          node-version: 24.19.0

      - name: Set up Corepack and Yarn
        run: |
          npm install --global corepack@0.35.0
          corepack enable
          corepack install --global yarn@4.18.0

      - name: Install JS dependencies
        run: yarn install --immutable

      - name: Run JavaScript tests
        run: yarn test:js

      - name: Build assets
        run: |
          yarn build
          yarn build:css

      - name: Database setup
        run: |
          bundle exec rails db:prepare

      - name: Run Rubocop
        run: |
          bundle exec rubocop --parallel

      - name: Run test
        run: |
          bundle exec rails test
