name: Ruby

on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

env:
  CI: "true"
  PGHOST: localhost
  PGUSER: postgres
  PGPASSWORD: password
  RAILS_ENV: test

permissions:
  contents: read

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:18-alpine
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: password
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Set up Node.js
        uses: actions/setup-node@v6.4.0
        with:
          node-version: 20
          cache: yarn
          cache-dependency-path: yarn.lock

      - name: Install JS dependencies
        run: yarn install --frozen-lockfile

      - name: Build assets
        run: |
          yarn build
          yarn build:css

      - name: Database setup
        run: |
          bundle exec rails db:prepare

      - name: Run Rubocop
        run: |
          bundle exec rubocop --parallel

      - name: Run test
        run: |
          bundle exec rails test
